<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>xb</groupId>
    <artifactId>best-practice</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <spring-cloud.version>Hoxton.SR12</spring-cloud.version>
        <spring-cloud-alibaba.version>2.2.9.RELEASE</spring-cloud-alibaba.version>
        <springboot.version>2.3.12.RELEASE</springboot.version>
        <lombok.version>1.18.42</lombok.version>
        <fastjson.version>1.2.47</fastjson.version>
        <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
        <maven-war-plugin.version>2.3</maven-war-plugin.version>
        <spring-boot-maven-plugin.version>${springboot.version}</spring-boot-maven-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${springboot.version}</version>
                <!--这两句话很重要，要不然会爆红-->
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <optional>true</optional>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>${fastjson.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
            <!--避免每次maven update后程序变为java1.5-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot-maven-plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>${maven-war-plugin.version}</version>
                <configuration>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                </configuration>
            </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <profiles>
        <profile>
            <id>all</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <modules>
                <module>common_facade</module>
                <module>common_utils</module>
                <module>simple_crud</module>
                <module>complex_crud</module>
                <module>jenkins</module>
                <module>spring_demo</module>
                <module>spring_cloud</module>
                <module>data</module>
                <module>shiro_demo</module>
                <module>concurrency_demo</module>
                <module>front_end_study</module>
                <module>message_demo</module>
                <module>redis_demo</module>
                <module>persistence</module>
                <module>elk_demo</module>
                <module>java_basis</module>
                <module>algorithm_study</module>
                <module>gateway_demo</module>
                <module>exception_handler_demo</module>
                <module>nacos</module>
            </modules>
        </profile>
        <profile>
            <id>fundamentals</id>
            <modules>
                <module>common_facade</module>
                <module>common_utils</module>
                <module>java_basis</module>
                <module>algorithm_study</module>
                <module>concurrency_demo</module>
            </modules>
        </profile>
        <profile>
            <id>spring</id>
            <modules>
                <module>common_facade</module>
                <module>common_utils</module>
                <module>spring_demo</module>
                <module>simple_crud</module>
                <module>complex_crud</module>
                <module>exception_handler_demo</module>
                <module>front_end_study</module>
            </modules>
        </profile>
        <profile>
            <id>middleware</id>
            <modules>
                <module>common_facade</module>
                <module>common_utils</module>
                <module>data</module>
                <module>redis_demo</module>
                <module>message_demo</module>
                <module>elk_demo</module>
                <module>persistence</module>
                <module>jenkins</module>
                <module>shiro_demo</module>
            </modules>
        </profile>
        <profile>
            <id>cloud</id>
            <modules>
                <module>common_facade</module>
                <module>common_utils</module>
                <module>spring_cloud</module>
                <module>nacos</module>
                <module>gateway_demo</module>
            </modules>
        </profile>
    </profiles>
</project>
