server:
  port: 18080

spring:
  application:
    name: ai-chat
  datasource:
    url: jdbc:mysql://localhost:3306/best_practice?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: dy82341733
    driver-class-name: com.mysql.cj.jdbc.Driver


ai-chat:
  glm:
    chat-completions-url: https://open.bigmodel.cn/api/paas/v4/chat/completions
    embeddings-url: https://open.bigmodel.cn/api/paas/v4/embeddings
    authorization: ${GLM_AUTHORIZATION:}
